#!/bin/sh
# Exercise the --list option.

# Copyright 2016-2026 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# limit so don't run it by default.

. "${srcdir=.}/init.sh"; path_prepend_ ..

echo zoology zucchini > in || framework_failure_
cp in orig || framework_failure_

gzip -l in && fail=1
gzip -9 in || fail=1
gzip -l in.gz >out1 || fail=1
gzip -l in.gz | cat >out2 || fail=1
compare out1 out2 || fail=1

: >empty || framework_failure_
gzip empty || fail=1
gzip -l empty.gz >emptyout || fail=1
case $(cat emptyout) in
  *' -Inf% '*) ;;
  *) cat smallout; fail=1;;
esac

echo '' >small || framework_failure_
gzip small || fail=1
cat small.gz small.gz >smallx2.gz || framework_failure_
gzip -l smallx2.gz >smallout || fail=1
case $(cat smallout) in
  *' 2 '*' smallx2') ;;
  *) cat smallout; fail=1;;
esac

Exit $fail
