#!/bin/sh
# Check behavior of output to pipes

# Copyright 2023-2026 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# limit so don't run it by default.

. "${srcdir=.}/init.sh"; path_prepend_ ..

: ${GREP=grep}
unset GREP_OPTIONS

sleep 0.01 && sleep_amount=0.01 || sleep_amount=1

echo a >a && echo b >b || framework_failure_
gzip -k a && gzip -k b || fail=1

# get_underlying_status CMD MINFAIL
# ---------------------------------
# Assign to the variable underlying_status the exit status of the command CMD.
# Treat all exit statuses in the range MINFAIL..127
# as if they were MINFAIL.
get_underlying_status() {
  underlying_status=$(
    (($trap_pipe '' PIPE
      sleep $sleep_amount
      eval "$1"
      echo $? >&3) | : ) 3>&1)
  test $2 -le $underlying_status && test $underlying_status -le 127 &&
    underlying_status=$2
}

# Check that gzip etc. behave like cat etc. if the output is a broken pipe.
for trap_pipe in trap :; do
  get_underlying_status 'cat <a.gz' 1
  cat_status=$underlying_status

  for cmd in 'gunzip' 'gunzip -q' 'gzip -d' 'gzip -dq' \
             'zcat' 'zcmp - b.gz' 'zdiff - b.gz' 'zgrep a'; do
    cmd_status=$( (($trap_pipe '' PIPE
                    sleep $sleep_amount
                    $cmd <a.gz
                    echo $? >&3) | : ) 3>&1)
    minfail=2
    case $cmd in
      zcmp*) get_underlying_status 'cmp - b <a' $minfail;;
      zdiff*) get_underlying_status 'diff - b <a' $minfail;;
      zgrep*) get_underlying_status '$GREP a <a' $minfail;;
      *) underlying_status=$cat_status minfail=1;;
    esac
    test $minfail -lt $cmd_status && test $cmd_status -lt 128 && cmd_status=1
    test $underlying_status -eq $cmd_status || fail=1
  done
done

Exit $fail
